# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2020-03-08 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='', max_length=200)),
                ('release_date', models.DateTimeField()),
                ('esrb_rating', models.CharField(default='', max_length=150)),
                ('played_once', models.BooleanField(default=False)),
                ('played_times', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
